name: Deploy Console Web to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.CONSOLE_VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.CONSOLE_VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  push:
    tags:
      - 'cw-v*.*.*'

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.CONSOLE_VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.CONSOLE_VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.CONSOLE_VERCEL_TOKEN }}